runtime: java
env: flex
service: default

handlers:
  - url: /.*
    script: this field is required, but ignored
    
manual_scaling:
  instances: 1
  
readiness_check:
    app_start_timeout_sec: 1800